print("========================")
print("Cek Berat Badan Idealmu")
print("========================")
nama = str(input("Masukkan Nama Anda: ")).title()
tb = float(input("Masukkan Tinggi Badan Anda: "))
bb_i = float(tb-100)-((tb-100)*0.1)
print("========================")
print("Hasil Berat Badan Ideal")
print("========================")
print(f"Nama: {nama}")
print(f"Tinggi Badan: {tb}")
print(f"Berat Badan: {bb_i}")
print("========================")
print("------Terimakasih------")
print("========================")
